[[grok]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a3fc8b6cb4bf241211e3712f3da0c14bf99aeb7"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "fcae591d3d3016cc67ec09f1ac1d8ea854ce48416ffc25032d8866ad0c28ef15"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.aarch64-linux-gnu-cxx11.tar.gz"
[[grok]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f632b501e2dd51c0a91f3ebed018c1e1faae0735"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "3d52c5a6c10addf7e967f2bb63e34d9d5ed4927525e09ed2797e4983be550ccd"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.i686-linux-gnu-cxx11.tar.gz"
[[grok]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e25afce70a1268abc9cc50e314e6c39857d6a87"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "372acc6ea85ab68a7b68ff7a1cb10935f62f488e4f52545fefde594407f81075"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.powerpc64le-linux-gnu-cxx11.tar.gz"
[[grok]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25dce45ad5290e5ea52182d0bd39d19f971d2d77"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "e1626c163be3dfc1d65eda15fa07fa73f3aef25fc2c4cabf4a59139239da4d7c"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.7+0/grok.v20.3.7.x86_64-linux-gnu-cxx11.tar.gz"
