[[grok]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e030b4e86fedaac7e518ff9ee2de7838081f1e7"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "30238cf073f3163c849b4de1a8808da609fa56de961c6a607278d2c8bc680324"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.aarch64-linux-gnu-cxx11.tar.gz"
[[grok]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9dccbc8185878f99c2088942b100a69fc5eb3d53"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "440af1a92251da82cbcf3d132842e430287fd2a318e63879b9ac6f556c581ea0"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.i686-linux-gnu-cxx11.tar.gz"
[[grok]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a305b27468ddfcd813ad578e583b232d94e4738"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "3c3c82aa0c1c8546280a73e8ed157d62a19224bca1f4acb0718c2a144a84962b"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[grok]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "535ef4fc2401a88e213a4cb699802417e64df69a"
libc = "glibc"
os = "linux"

    [[grok.download]]
    sha256 = "58fb7dc30478b6bfc8d094c4ceaaf647b2df2e0d2e3636725e465f25b9167b39"
    url = "https://github.com/JuliaBinaryWrappers/grok_jll.jl/releases/download/grok-v20.3.3+0/grok.v20.3.3.x86_64-linux-gnu-cxx11.tar.gz"
