# Autogenerated wrapper script for grok_jll for x86_64-linux-gnu-cxx11
export grk_compress, grk_decompress, grk_dump, grk_transcode, libgrokj2k, libgrokj2kcodec

using Fmt_jll
using JpegTurbo_jll
using Libtiff_jll
using LittleCMS_jll
using Zlib_jll
using libpng_jll
JLLWrappers.@generate_wrapper_header("grok")
JLLWrappers.@declare_library_product(libgrokj2k, "libgrokj2k.so.1")
JLLWrappers.@declare_library_product(libgrokj2kcodec, "libgrokj2kcodec.so.1")
JLLWrappers.@declare_executable_product(grk_compress)
JLLWrappers.@declare_executable_product(grk_decompress)
JLLWrappers.@declare_executable_product(grk_dump)
JLLWrappers.@declare_executable_product(grk_transcode)
function __init__()
    JLLWrappers.@generate_init_header(Fmt_jll, JpegTurbo_jll, Libtiff_jll, LittleCMS_jll, Zlib_jll, libpng_jll)
    JLLWrappers.@init_library_product(
        libgrokj2k,
        "lib/libgrokj2k.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libgrokj2kcodec,
        "lib/libgrokj2kcodec.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        grk_compress,
        "bin/grk_compress",
    )

    JLLWrappers.@init_executable_product(
        grk_decompress,
        "bin/grk_decompress",
    )

    JLLWrappers.@init_executable_product(
        grk_dump,
        "bin/grk_dump",
    )

    JLLWrappers.@init_executable_product(
        grk_transcode,
        "bin/grk_transcode",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
